---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mycart-backend
  namespace: mycart
spec:
  selector:
    matchLabels:
      app: mycart
      tier: backend
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: mycart
        tier: backend
    spec:
      containers:
      - name: myappbe
        image: sasijakki/mycart-backend:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: "MY_DB_USER"
            value: "mysqluser"
          - name: "MY_DB_PASS"
            value: "password"
          - name: "MY_DB_NAME"
            value: "mydyatadb"
          - name: "MY_DB_HOST_WRITE"
            value: "mysql-0.msql"
          - name: "MY_DB_HOST_READ"
            value: "mysql-read"